name: poker_hand_history
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  sqflite: 0.9.0
  path_provider: "0.4.1"
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/clubs.png
    - images/diamonds.png
    - images/hearts.png
    - images/spades.png